### ISSUE TITLE
where I  can find result file

### ISSUE THREAD

**Issue by francescoyang** [desh2608/crnn-relation-classification#7]
Hi  where I  can find result file

**Comment by francescoyang** [comment]
IOError: [Errno 2] No such file or directory: './results/crnn-max-all-features_correct.txt'

**Comment by francescoyang** [comment]
IOError: [Errno 2] No such file or directory: './ddi/train_data.txt'

where I  can find this train_data

**Comment by desh2608** [comment]
The datasets cannot be publicly distributed. You would have to contact the authorized people for that. Please look at this: https://github.com/desh2608/crnn-relation-classification/issues/1

**Comment by reastwood** [comment]
Hi @francescoyang. It looks like you got the data from someone else and posted it to the Chinese Software Developer Network: https://download.csdn.net/download/acanoe/10652813. We found this because Zhao Wanqing also posted an illegal copy to https://github.com/Hankers3/i2b2-dataset and listed you as his source.
As @desh2608 had kindly pointed out, these datasets cannot be publicly distributed. Whoever gave a copy to you violated their DUA, and you are not authorized to distribute it on CSDN. Please remove it immediately.
